"""Add business logging tables

Revision ID: 72abde6824ab
Revises: 8c31d1025aed
Create Date: 2026-05-10 21:07:36.783826

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72abde6824ab'
down_revision: Union[str, Sequence[str], None] = 'b3c4d5e6f7a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('communication_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('direction', sa.String(), nullable=True),
    sa.Column('contact_id', sa.String(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_communication_logs_contact_id'), 'communication_logs', ['contact_id'], unique=False)
    op.create_index(op.f('ix_communication_logs_id'), 'communication_logs', ['id'], unique=False)
    op.create_index(op.f('ix_communication_logs_type'), 'communication_logs', ['type'], unique=False)
    op.create_table('deal_stage_history',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('deal_id', sa.String(), nullable=True),
    sa.Column('old_stage', sa.String(), nullable=True),
    sa.Column('new_stage', sa.String(), nullable=True),
    sa.Column('changed_at', sa.DateTime(), nullable=True),
    sa.Column('changed_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deal_stage_history_deal_id'), 'deal_stage_history', ['deal_id'], unique=False)
    op.create_index(op.f('ix_deal_stage_history_id'), 'deal_stage_history', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_deal_stage_history_id'), table_name='deal_stage_history')
    op.drop_index(op.f('ix_deal_stage_history_deal_id'), table_name='deal_stage_history')
    op.drop_table('deal_stage_history')
    op.drop_index(op.f('ix_communication_logs_type'), table_name='communication_logs')
    op.drop_index(op.f('ix_communication_logs_id'), table_name='communication_logs')
    op.drop_index(op.f('ix_communication_logs_contact_id'), table_name='communication_logs')
    op.drop_table('communication_logs')
    # ### end Alembic commands ###
